#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob globstar

METHOD="moe"  # NOTE: valid options are "joint_elbo", "poe", and "moe"
LIKELIHOOD_M1="laplace"
LIKELIHOOD_M2="laplace"
DIR_DATA="$HOME/Datasets"
DIR_CLF="$PWD/trained_classifiers/trained_clfs_mst"
DIR_EXPERIMENT="$PWD/runs/MNIST_SVHN/${METHOD}/${LIKELIHOOD_M1}_${LIKELIHOOD_M2}"
DIR_FID="$DIR_DATA/MNIST_SVHN"

python3 main_svhnmnist.py --dir_data=$DIR_DATA \
			--dir_clf="$DIR_CLF" \
			--dir_experiment="$DIR_EXPERIMENT" \
			--dir_fid=$DIR_FID \
			--method=$METHOD \
			--style_m1_dim=0 \
			--style_m2_dim=0 \
			--class_dim=20 \
			--beta=1 \
			--likelihood_m1=$LIKELIHOOD_M1 \
			--likelihood_m2=$LIKELIHOOD_M2 \
			--batch_size=256 \
			--initial_learning_rate=0.001 \
			--eval_freq=1 \
			--eval_freq_fid=1 \
			--data_multiplications=1 \
			--num_hidden_layers=1 \
			--end_epoch=30 \
                        --reweight_rec=0 \

