#!/usr/bin/env bash
set -eo pipefail
shopt -s nullglob globstar

# define TMPDIR, if it's empty
if [[ -z "$TMPDIR" ]]; then
    TMPDIR="/tmp"
fi
echo "TMPDIR: $TMPDIR"

# activate conda env
# eval "$(conda shell.bash hook)"
# conda activate mopoe
# echo "CONDA_PREFIX: $CONDA_PREFIX"

METHOD="poe"  # NOTE: valid options are "joint_elbo", "poe", and "moe"
LIKELIHOOD_M1="laplace"
LIKELIHOOD_M2="normal"
DIR_DATA="$HOME/Datasets"
DIR_CLF="$PWD/trained_classifiers/trained_clfs_mst"
DIR_EXPERIMENT="$PWD/runs/MNIST_GM/${METHOD}/${LIKELIHOOD_M1}_${LIKELIHOOD_M2}"

# copy data to $TMPDIR
cp -r "${DIR_DATA}/MNIST" "${TMPDIR}/"

python3 main_gmmnist.py --dir_data=$TMPDIR \
            --dir_clf="$DIR_CLF" \
            --dir_experiment="$DIR_EXPERIMENT" \
            --method=$METHOD \
            --style_m1_dim=0 \
            --style_m2_dim=0 \
            --class_dim=2 \
            --beta=1 \
            --likelihood_m1=$LIKELIHOOD_M1 \
            --likelihood_m2=$LIKELIHOOD_M2 \
            --batch_size=256 \
            --initial_learning_rate=0.001 \
            --eval_freq=1 \
            --eval_freq_fid=1 \
            --data_multiplications=1 \
            --num_hidden_layers=1 \
            --end_epoch=40 \
	    --GM_radius=5 \
            --reweight_rec=0 \

